import config from '../../config/site.config.json'
import profile from '../../content/profile.json'
import { findProjects, findSkills, mapToEvidence } from './matching'

const sourceUrl = () => profile.profile.sources?.find(source => source.label === 'Reference portfolio')?.url || ''

export async function registerWebMCPTools(ui) {
    if (typeof document.modelContext?.registerTool !== 'function') return false
    const activity = (tool, summary) => ui.onActivity?.({ tool, summary, at: new Date().toLocaleTimeString() })
    const register = definition => document.modelContext.registerTool(definition)

    await register({ name: 'get_profile_snapshot', description: `Get ${config.name}'s role, domains of expertise, availability, and source-attributed public profile snapshot.`, inputSchema: { type: 'object', properties: {}, additionalProperties: false }, annotations: { readOnlyHint: true }, execute: async () => { ui.navigate('/about'); activity('get_profile_snapshot', 'Opened the profile evidence view'); return profile.profile } })
    await register({ name: 'search_expertise', description: `Search ${config.name}'s skill inventory by technology, category, experience, or level; filters the visible stack matrix.`, inputSchema: { type: 'object', properties: { query: { type: 'string' }, category: { type: 'string' }, min_years: { type: 'number', minimum: 0, maximum: 50 } }, additionalProperties: false }, annotations: { readOnlyHint: true }, execute: async ({ query = '', category = 'all', min_years: minYears = 0 }) => { const matches = findSkills(profile.skills, query, { category, minYears }); ui.onSkillFilter?.({ query, category, minYears }); ui.navigate('/stack'); activity('search_expertise', `Filtered the Tech Stack to ${matches.length} matching skills`); return { query: { query, category, min_years: minYears }, match_count: matches.length, matches: matches.map(({ name, category: skillCategory, years, level, source }) => ({ name, category: skillCategory, years, level, source })), human_view: '/stack' } } })
    await register({ name: 'find_relevant_work', description: `Find ${config.name}'s project evidence relevant to a technical requirement and show matching work in the portfolio.`, inputSchema: { type: 'object', properties: { requirement: { type: 'string' }, include_active: { type: 'boolean' } }, additionalProperties: false }, annotations: { readOnlyHint: true }, execute: async ({ requirement = '', include_active: includeActive = true }) => { const projects = findProjects(profile.projects, requirement, { includeActive }); ui.navigate('/projects'); activity('find_relevant_work', `Opened ${projects.length} matching portfolio entries`); return { requirement, match_count: projects.length, projects: projects.map(({ id, title, status, tags, evidence }) => ({ id, title, status, tags, evidence })), human_view: '/projects' } } })
    await register({ name: 'get_case_study_evidence', description: `Read a source-labelled technical case study from ${config.name}'s portfolio by project ID.`, inputSchema: { type: 'object', properties: { project_id: { type: 'string' } }, required: ['project_id'], additionalProperties: false }, annotations: { readOnlyHint: true }, execute: async ({ project_id: projectId }) => { const project = profile.projects.find(item => item.id === projectId); if (!project) return { error: 'Unknown project ID. Use find_relevant_work first.' }; ui.navigate(project.slug ? `/projects/${project.slug}` : '/projects'); activity('get_case_study_evidence', `Opened evidence for ${project.title}`); return { ...project, source_url: project.evidence_url || sourceUrl() } } })
    await register({ name: 'map_requirements_to_evidence', description: `Map a technical brief to ${config.name}'s skills and project evidence. Shows coverage and gaps without making suitability guarantees.`, inputSchema: { type: 'object', properties: { requirements: { type: 'array', minItems: 1, maxItems: 8, items: { type: 'string', minLength: 2, maxLength: 120 } }, include_active: { type: 'boolean' } }, required: ['requirements'], additionalProperties: false }, annotations: { readOnlyHint: true }, execute: async ({ requirements, include_active: includeActive = true }) => { const result = { requirements, include_active: includeActive, mapping: mapToEvidence(profile, requirements, { includeActive }) }; ui.onFitMap?.(result); ui.navigate('/projects'); activity('map_requirements_to_evidence', `Mapped ${requirements.length} requirements to the visible evidence matrix`); return { ...result, human_view: '/projects', disclaimer: 'Evidence map only — not a guarantee of suitability, capacity, or outcome.' } } })
    await register({ name: 'compare_engagement_options', description: `Compare ${config.name}'s published engagement options and display them for the visitor to review.`, inputSchema: { type: 'object', properties: { types: { type: 'array', items: { type: 'string' }, maxItems: 4 } }, additionalProperties: false }, annotations: { readOnlyHint: true }, execute: async ({ types = [] }) => { const options = !types.length ? profile.engagement_options : profile.engagement_options.filter(option => types.includes(option.type)); ui.onEngagementOptions?.(options); ui.navigate('/projects'); activity('compare_engagement_options', `Displayed ${options.length} engagement options`); return { options, human_view: '/projects' } } })
    await register({ name: 'create_discovery_brief', description: `Create a reviewable discovery brief for ${config.name}'s portfolio. It is saved only in this browser session and is never sent.`, inputSchema: { type: 'object', properties: { goals: { type: 'array', items: { type: 'string' }, minItems: 1, maxItems: 8 }, constraints: { type: 'array', items: { type: 'string' }, maxItems: 8 }, questions: { type: 'array', items: { type: 'string' }, maxItems: 8 } }, required: ['goals'], additionalProperties: false }, execute: async input => { const brief = { ...input, created_at: new Date().toISOString(), status: 'reviewable_not_sent' }; ui.onDiscoveryBrief?.(brief); ui.navigate('/projects'); activity('create_discovery_brief', 'Created a reviewable discovery brief'); return { status: brief.status, brief, human_view: '/projects' } } })
    await register({ name: 'prepare_contact_request', description: `Fill out (never submit) ${config.name}'s contact form with a project inquiry for the visitor to review and send themselves.`, inputSchema: { type: 'object', properties: { name: { type: 'string', minLength: 1, maxLength: 120 }, email: { type: 'string', format: 'email', maxLength: 254 }, project_summary: { type: 'string', minLength: 1, maxLength: 1000 } }, required: ['name', 'email', 'project_summary'], additionalProperties: false }, execute: async input => { ui.onContactDraft?.({ name: input.name, email: input.email, message: input.project_summary, type: 'project' }); ui.navigate('/contact'); activity('prepare_contact_request', 'Filled a draft inquiry for human review; nothing was sent'); return { status: 'form_filled_awaiting_human_submit', fields: config.contactForm.fields, human_view: '/contact' } } })
    return true
}
