import config from '../../config/site.config.json'
import profile from '../../content/profile.json'
import './About.css'

function About() {
    const snapshot = profile.profile.marketplace_snapshot
    const about = profile.profile.about
    return <div className="about-page">
        <section className="about-hero section"><div className="container"><div className="status-badge"><div className="status-dot animate"></div><span>{about.status}</span></div><h1 className="page-title"><span className="text-primary">&gt;</span> {about.title}</h1><div className="about-intro"><div className="intro-content"><p className="intro-lead">{about.lead}</p>{about.paragraphs.map(paragraph => <p key={paragraph} className="intro-text">{paragraph}</p>)}</div><div className="intro-stats"><div className="stat-box"><span className="stat-number">{profile.profile.experience_years}</span><span className="stat-label">Years Experience</span></div><div className="stat-box"><span className="stat-number">{snapshot.projects_worked_on}+</span><span className="stat-label">Projects Worked On</span></div><div className="stat-box"><span className="stat-number">{snapshot.rating}</span><span className="stat-label">Public Rating</span></div><div className="stat-box"><span className="stat-number">{snapshot.review_count}</span><span className="stat-label">Public Reviews</span></div></div></div></div></section>
        <section className="timeline-section section"><div className="container"><div className="section-header"><span className="font-mono text-primary">git log --oneline ./career</span></div><div className="timeline">{about.timeline.map(item => <article key={`${item.year}-${item.title}`} className="timeline-item"><div className="timeline-marker"><span className="material-symbols-outlined">work</span></div><div className="timeline-content card"><span className="timeline-year">{item.year}</span><h3 className="timeline-title">{item.title}</h3><p className="timeline-company">{item.company}</p><p className="timeline-description">{item.description}</p></div></article>)}</div></div></section>
        <section className="certifications-section section"><div className="container"><div className="section-header"><span className="font-mono text-primary">ls ./certifications/</span><span className="font-mono text-dim">{profile.profile.workspace_premium ? 'Premium workspace' : 'Public profile'}</span></div><div className="cert-grid">{about.certifications.map(certification => <article key={certification.name} className="cert-card card"><div className="cert-icon"><span className="material-symbols-outlined">workspace_premium</span></div><div className="cert-info"><h3 className="cert-name">{certification.name}</h3><p className="cert-issuer">{certification.issuer}</p></div><div className="cert-verified"><span className="material-symbols-outlined">verified</span></div></article>)}</div></div></section>
        <section className="values-section section"><div className="container"><div className="section-header"><span className="font-mono text-primary">cat ./work_philosophy.md</span></div><div className="values-grid">{about.values.map(value => <article key={value.title} className="value-card card"><span className="material-symbols-outlined">{value.icon}</span><h3>{value.title}</h3><p>{value.description}</p></article>)}</div></div></section>
        <section className="values-section section"><div className="container"><div className="section-header"><span className="font-mono text-primary">cat ./sources.json</span></div><div className="values-grid">{profile.profile.sources.map(source => <a key={source.url} href={source.url} target="_blank" rel="noopener noreferrer" className="value-card card"><span className="material-symbols-outlined">source</span><h3>{source.label}</h3><p>Verified {source.verified_on}</p></a>)}</div></div></section>
    </div>
}

export default About
